### ISSUE TITLE
Operation returned an invalid status code 'Forbidden'

### ISSUE THREAD

**Issue by freshdev1** [Microsoft/PowerBI-CSharp#100]
Hello Guys, I am new to PowerBI, and is stuck with this error.
What I am doing:
My `Main` function:
```
static void Main(string[] args)
        {
            try
            {
                var client = CreateClient().Result;
                var reports = client.Reports.GetReportsAsync(workspaceCollectionName, workspaceId).Result;
            }
            catch(Exception ex)
            {
                Console.Write(ex);
            }

            Console.ReadLine();
            
        }
```

My `CreateClient` function:
```
static async Task<PowerBIClient> CreateClient()
        {
            if (accessKeys == null)
            {
                //var enteredKey = userInput.EnterOptionalParam("Access Key", "Auto select");
                if (!string.IsNullOrWhiteSpace(accessKey1))
                {
                    //accessKey = accessKey;
                    accessKeys = new WorkspaceCollectionKeys()
                    {
                        Key1 = accessKey1,
                        Key2 = accessKey2
                    };
                }
            }

            // Create a token credentials with "AppKey" type
            var credentials = new TokenCredentials(accessKeys.Key1, "AppKey");

            // Instantiate your Power BI client passing in the required credentials
            var client = new PowerBIClient(credentials);

            // Override the api endpoint base URL.  Default value is https://api.powerbi.com
            client.BaseUri = new Uri(apiEndpointUri);

            return await Task.FromResult(client);
        }
```

I was getting the same error in the `ProvisionSample` here: https://github.com/Azure-Samples/power-bi-embedded-integrate-report-into-web-app

Stacktrace:
```
   at Microsoft.PowerBI.Api.V1.Reports.<GetReportsWithHttpMessagesAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PowerBI.Api.V1.ReportsExtensions.<GetReportsAsync>d__1.MoveNext()
```

Can anyone help me on this?

**Comment by freshdev1** [comment]
Sorry guys, my bad. I had been using bad WorkspaceCollectionName`. I had entered `WorkspaceName`, rather than `WorkspaceCollectionName` Things resolved now.
