### ISSUE TITLE
When using client.Reports.GetReports() or any list receive Forbidden 

### ISSUE THREAD

**Issue by ArbelaBrandon** [Microsoft/PowerBI-CSharp#110]
Hello, When using this, having registered a native application and doing a basic client.Reports.GetReports() or any other list from DataSets, etc. always returns a Forbidden error message:

"Operation returned an invalid status code 'Forbidden'"

Here is the stack trace:

   at Microsoft.PowerBI.Api.V2.Reports.<GetReportsInGroupWithHttpMessagesAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PowerBI.Api.V2.ReportsExtensions.<GetReportsInGroupAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PowerBI.Api.V2.ReportsExtensions.GetReportsInGroup(IReports operations, String groupId)
   at ArbelaDataOppsConsole.Program.DoStuff() in c:\users\datap\documents\visual studio 2015\Projects\ArbelaDataOppsConsole\ArbelaDataOppsConsole\Program.cs:line 48
   at ArbelaDataOppsConsole.Program.Main(String[] args) in c:\users\datap\documents\visual studio 2015\Projects\ArbelaDataOppsConsole\ArbelaDataOppsConsole\Program.cs:line 29
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

Correct access has been granted for this application within the tenant? Let me know what else is needed in order to support the resolution of this issue.

**Comment by ArbelaBrandon** [comment]
Ok so this was related to other similar issues. It has 100% to do with the correct ApiURL being used and further also making sure your not trying to access the root group. Use the client.Groups.GetGroups() and the returned values then can be used in order to get desired details.

**Comment by SebastianGuerreroCardenas** [comment]
I am having this issue, is there a solution to this?

**Comment by ali-hamud** [comment]
Hi,
can you please tell if you still have problems?
if yes, please give request Id of failed request.

**Comment by JonJam** [comment]
I am seeing something with client.Reports.GetReportAsync(reportId).

Here is the request information and stack trace:
**Request URI**
https://api.powerbi.com/v1.0/myorg/reports/455b8ec0-9121-43a1-a4f0-6a91bc1bab33

**Request ID**
0e7132a9-5e7f-4418-9fff-c57d6c07a3e2

**Response Content**
{"error":{"code":"PowerBINotAuthorizedException","pbi.error":{"code":"PowerBINotAuthorizedException","parameters":{},"details":[],"exceptionCulprit":1}}}

**Stack Trace**
   at Microsoft.PowerBI.Api.V2.Reports.<GetReportWithHttpMessagesAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PowerBI.Api.V2.ReportsExtensions.<GetReportAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

**Comment by ali-hamud** [comment]
one more question, is this report exists in a specific workspace? or it's defined in "My Workspace"?

**Comment by JonJam** [comment]
@ali-hamud For me it is in a specific work space, not "My Workspace".

**Comment by ali-hamud** [comment]
so please use GetReportInGroupAsync(reportId, groupId)
groupId is the workspaceId.

**Comment by JonJam** [comment]
@ali-hamud Thanks
