### ISSUE TITLE
Operation returned an invalid status code 'NotFound' checking client.Imports.GetImportByIdAsync

### ISSUE THREAD

**Issue by alanwales** [Microsoft/PowerBI-CSharp#94]
Since one week ago our report upload script broke since calling GetImportByIdAsync returns a "NotFound" status. We have upgraded to 1.1.10 but the issue is still there, we suspect that the SDK and Api are out of sync.

StackTrace:
   at Microsoft.PowerBI.Api.V1.Imports.<GetImportByIdWithHttpMessagesAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PowerBI.Api.V1.ImportsExtensions.<GetImportByIdAsync>d__7.MoveNext()

StatusCode:
System.Net.HttpStatusCode.NotFound

**Comment by tomkerkhove** [comment]
## Context
It appears like there is a limitation where you can import a file **200 times** for a single workspace. After that all new imports will no longer be found for that same workspace. 

This begs me with the following questions:

- Is this by design (I hope not, to be honest)
- Is this documented somewhere?

## Reproducing the issue
This is a snippet that reproduces the behavior:
```var workspaceRequest = new CreateWorkspaceRequest();
var workspaceResponse = await client.Workspaces.PostWorkspaceWithHttpMessagesAsync(collectionName, workspaceRequest);

for (int counter = 1; counter < 205; counter++)
{
	try
	{
		using (var reportFileStream = File.OpenRead(filePath.Trim('"')))
		{
			var workspaceId = workspaceResponse.Body.WorkspaceId;
			var import = await client.Imports.PostImportWithFileAsync(collectionName, workspaceId, reportFileStream, datasetName);
			var retrievedImport = await client.Imports.GetImportByIdAsync(collectionName, workspaceId, import.Id);
			Console.WriteLine($"Attempt #{counter} succeeded - {retrievedImport?.ImportState}");
		}
	}
	catch (Exception ex)
	{
		Console.WriteLine($"Attempt #{counter} failed - {ex.Message}");
	}
}```

Unfortunately this is a blocker at the moment for us, hopefully this is something that can be fixed easily?
This repro is based on todays codebase.

**Comment by alanwales** [comment]
I couldn't find an exact limit on the imports but it does indeed look like 200 is a common limitation number

http://markvsql.com/2015/09/current-power-bi-service-limits

**Comment by tomkerkhove** [comment]
If that would be the cause of the issue here I'm wondering:

- Where this is documented? Can't find any limitations on azure.com on Power BI Embedded which should be there, even if it's just pointing to Power BI limits.
- Why the initial import succeeded from a consumer perspective, if it would be a limit I'd expect an exception to be thrown or something
- Why we can't just publish the new import and drop the oldest import in the workspace?

Is there a GitHub repo for service-side issues/feature requests?

**Comment by mikeblakeuk** [comment]
Workspaces are limited to 200. It looks like Groups are not (using the new V2 service). Maybe upgrade?
Note; the real exception is in the body / Header of the response.

**Comment by tomkerkhove** [comment]
@mikeblakeuk  Thanks for the response - With upgrading you mean to Power BI Premium or v2 of Power BI Embedded?

**Comment by mikeblakeuk** [comment]
V2 of the Client

**Comment by tomkerkhove** [comment]
We'll look into upgrading then, since there is a new version feel free to close this issue.
I'll create a new one if there is an issue

**Comment by simonbourdeau** [comment]
What ever happened to backwards compatibility? Now we need to upgrade SDK? Yesterday it was the whole PowerBi workspace structure. This PowerBi embedded experience has been the worst. We are through with PowerBi.

**Comment by ali-hamud** [comment]
Hi @simonbourdeau,
what is not working for you?

**Comment by simonbourdeau** [comment]
Hi Ali,

we have reports on cached data that have been maintained updated by
importing them every morning for the last months. We can no longer import
the refreshed reports. This creates a live bug in our system.

**Comment by ali-hamud** [comment]
Hi,
if something stopped working in your end, this could be a bug that we need to fix.
can you please give more details?
what api call is failing for you? what error do you see?
please send a request Id as well, you can find it in network traffic tool like fiddler.

**Comment by simonbourdeau** [comment]
I currently have a ticket with Microsoft's Shravan Kumar Shetty (
v-shshet@microsoft.com) regarding this.

I don't trust this channel to share session information.

Thanks,

…


Simon Bourdeau

Backend Engineer

MetroQuest
