### ISSUE TITLE
can't import EXCEL to Power BI.com

### ISSUE THREAD

**Issue by zhll2046** [Microsoft/PowerBI-CSharp#96]
I was following this sample 
https://github.com/Microsoft/PowerBI-CSharp/tree/master/samples/consoleapp/getting-started-for-dotnet-import

And it works fine when uploading a pbix to my workspace in PowerBI.com.
However when trying to import an EXCEL file I got error. As the online documentation(https://msdn.microsoft.com/en-us/library/mt243840.aspx) says the API supports uploading Excel, so could you please help to figure out this issue?

 The stacktrace saying

>    at System.Net.HttpWebRequest.GetResponse()
   at PBIGettingStarted.Program.Import(String url, String fileName) in C:\PowerBI Dev\PBIGettingStartedimport\PBIGettingStarted\Program.cs:line 609
   at PBIGettingStarted.Program.Main(String[] args) in C:\PowerBI Dev\PBIGettingStartedimport\PBIGettingStarted\Program.cs:line 56
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by zhll2046** [comment]
@ali-hamud @wbreza

**Comment by zhll2046** [comment]
Any one?
