### ISSUE TITLE
PostImportWithFile returns "Internal Server Error"

### ISSUE THREAD

**Issue by albin-ipmg** [Microsoft/PowerBI-CSharp#99]
client.Imports.PostImportWithFile returns "Internal Server Error" when a fairly large PBIX file is imported (approx. 700MB). After the exception is thrown, we still end up with the PBIX file in the workspace but with multiple copies of the same report as if the import process was run multiple times, as well as multiple datasets. The number of copies in the workspace appears to be somewhat random, as one time there may be 2 copies of the file in the workspace and at other times 3 or 4. All multiple copies have different report id. If then any instance of the multiple copies is deleted by report id, this also then deletes all other duplicated instances despite different report id values. The above exception is not thrown for a PBIX file which has smaller size of around 400MB and that one imports without any issues. 

------------------------------

Operation returned an invalid status code 'InternalServerError'

   at Microsoft.PowerBI.Api.V1.Imports.<PostImportFileWithHttpMessage>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PowerBI.Api.V1.ImportsExtensions.PostImportWithFile(IImports operations, String collectionName, String workspaceId, Stream fileStream, String datasetDisplayName, String nameConflict)
   at Ipmg.InSightCore.Service.PowerBiService.<ImportReport>d__15.MoveNext()

**Comment by albin-ipmg** [comment]
For anyone with same issue, the problem is in using the base url https://api.powerbi.com. As per Microsoft support, when using this base url and importing large PBIX files, it has a tendency to timeout the file stream, thus throwing the exception. Microsoft support provided a direct URL to our local Power Bi Workspace cluster and the issue was resolved.
